#**Tugas Praktikum Natural Language Processing**

#**Nama : Gavrilla Claudia**

#**NIM : 21110004**

#**Kelas : S1SD02A**

In [1]:
pip install PyPDF2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 4.8 MB/s eta 0:00:00


In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [3]:
import PyPDF2
import pandas as pd
from gensim.models import Word2Vec, FastText
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import CountVectorizer

#**1. One hot encoding**

In [4]:
# Membaca teks dari file PDF
def extract_text_from_pdf(pdf_file):
    text = ""
    with open(pdf_file, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for page_number in range(len(reader.pages)):
            text += reader.pages[page_number].extract_text()
    return text

# Mendapatkan teks dari file PDF
pdf_file = 'MALIN_KUNDANG.pdf'
data = extract_text_from_pdf(pdf_file)

In [5]:
data

'MALIN KUNDANG \nPada suatu waktu, hiduplah sebuah keluarga nelayan di \npesisir pantai wilayah Sumatra. Keluarga tersebut terdiri \ndari ayah, ibu dan seorang anak laki-laki yang diberi nama \nMalin Kundang. Karena kondisi keuangan keluarga yang \nmemprihatinkan, sang ayah memutuskan untuk mencari \nnafkah di negeri seberang dengan mengarungi lautan yang \nluas.\nMaka tinggallah si Malin dan ibunya di gubug mereka. Semingg u, dua minggu, sebulan, dua \nbulan bahkan sudah 1 tahun lebih lamanya, ayah Malin tidak  juga kembali ke kampung \nhalamannya. Sehingga ibunya harus menggantikan posisi ayah Malin untuk mencari nafkah. \nMalin termasuk anak yang cerdas tetapi sedikit nakal. Ia  sering mengejar ayam dan \nmemukulnya dengan sapu. Suatu hari ketika Malin sedang me ngejar ayam, ia tersandung \nbatu dan lengan kanannya luka terkena batu. Luka terse but menjadi berbekas dilengannya \ndan tidak bisa hilang. \nSetelah beranjak dewasa, Malin Kundang merasa kasihan dengan ibunya yang banting

In [6]:
token = sent_tokenize(data)
teks = ''.join(token)

corpus = word_tokenize(teks)
corpus

['MALIN',
 'KUNDANG',
 'Pada',
 'suatu',
 'waktu',
 ',',
 'hiduplah',
 'sebuah',
 'keluarga',
 'nelayan',
 'di',
 'pesisir',
 'pantai',
 'wilayah',
 'Sumatra.Keluarga',
 'tersebut',
 'terdiri',
 'dari',
 'ayah',
 ',',
 'ibu',
 'dan',
 'seorang',
 'anak',
 'laki-laki',
 'yang',
 'diberi',
 'nama',
 'Malin',
 'Kundang.Karena',
 'kondisi',
 'keuangan',
 'keluarga',
 'yang',
 'memprihatinkan',
 ',',
 'sang',
 'ayah',
 'memutuskan',
 'untuk',
 'mencari',
 'nafkah',
 'di',
 'negeri',
 'seberang',
 'dengan',
 'mengarungi',
 'lautan',
 'yang',
 'luas.Maka',
 'tinggallah',
 'si',
 'Malin',
 'dan',
 'ibunya',
 'di',
 'gubug',
 'mereka.Semingg',
 'u',
 ',',
 'dua',
 'minggu',
 ',',
 'sebulan',
 ',',
 'dua',
 'bulan',
 'bahkan',
 'sudah',
 '1',
 'tahun',
 'lebih',
 'lamanya',
 ',',
 'ayah',
 'Malin',
 'tidak',
 'juga',
 'kembali',
 'ke',
 'kampung',
 'halamannya.Sehingga',
 'ibunya',
 'harus',
 'menggantikan',
 'posisi',
 'ayah',
 'Malin',
 'untuk',
 'mencari',
 'nafkah.Malin',
 'termasuk',
 'anak

In [7]:
hasil_encoding = pd.get_dummies(corpus)
hasil_encoding

!  '  ''  ,  -buahan  -manggil  -masing  -mutar  .  ..  ...  yata  \
0      0  0   0  0        0         0        0       0  0   0  ...     0   
1      0  0   0  0        0         0        0       0  0   0  ...     0   
2      0  0   0  0        0         0        0       0  0   0  ...     0   
3      0  0   0  0        0         0        0       0  0   0  ...     0   
4      0  0   0  0        0         0        0       0  0   0  ...     0   
...   .. ..  .. ..      ...       ...      ...     ... ..  ..  ...   ...   
39398  0  0   0  1        0         0        0       0  0   0  ...     0   
39399  0  0   0  0        0         0        0       0  0   0  ...     0   
39400  0  0   0  0        0         0        0       0  0   0  ...     0   
39401  0  0   0  0        0         0        0       0  0   0  ...     0   
39402  0  0   0  0        0         0        0       0  1   0  ...     0   

       yatim  yelamatkan  yet.Mereka  yik  yikan  yir  yuk  yut  zam  
0          0           0           0    0      0    0    0    0    0  
1          0           0           0    0      0    0    0    0    0  
2          0           0           0    0      0    0    0    0    0  
3          0           0           0    0      0    0    0    0    0  
4          0           0           0    0      0    0    0    0    0  
...      ...         ...         ...  ...    ...  ...  ...  ...  ...  
39398      0           0           0    0      0    0    0    0    0  
39399      0           0           0    0      0    0    0    0    0  
39400      0           0           0    0      0    0    0    0    0  
39401      0           0           0    0      0    0    0    0    0  
39402      0           0           0    0      0    0    0    0    0  

[39403 rows x 7629 columns]

from matplotlib import pyplot as plt
hasil_encoding['!'].plot(kind='hist', bins=20, title='!')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding["'"].plot(kind='hist', bins=20, title="'")
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding["''"].plot(kind='hist', bins=20, title="''")
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding[','].plot(kind='hist', bins=20, title=',')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding.plot(kind='scatter', x='!', y="'", s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding.plot(kind='scatter', x="'", y="''", s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding.plot(kind='scatter', x="''", y=',', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding.plot(kind='scatter', x=',', y='-buahan', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['T']
  ys = series['!']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = hasil_encoding.sort_values('T', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('T')
_ = plt.ylabel('!')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['T']
  ys = series["'"]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = hasil_encoding.sort_values('T', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('T')
_ = plt.ylabel("'")

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['T']
  ys = series["''"]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = hasil_encoding.sort_values('T', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('T')
_ = plt.ylabel("''")

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['T']
  ys = series[',']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = hasil_encoding.sort_values('T', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('T')
_ = plt.ylabel(',')

from matplotlib import pyplot as plt
hasil_encoding['!'].plot(kind='line', figsize=(8, 4), title='!')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding["'"].plot(kind='line', figsize=(8, 4), title="'")
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding["''"].plot(kind='line', figsize=(8, 4), title="''")
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
hasil_encoding[','].plot(kind='line', figsize=(8, 4), title=',')
plt.gca().spines[['top', 'right']].set_visible(False)

**Interpretasi Hasil :**

**Dari output di atas, kita dapat melihat bahwa pada indeks ke-5 dan indeks ke-19 simbol "," bernilai 1 yang menunjukkan bahwa ada kaitan antara simbol "," dan indeks tersebut atau bahwa simbol "," berada pada index ke-5 dan indeks ke-19 dalam konteks data ini.**



#**2. Hash**

In [8]:
from sklearn.feature_extraction.text import HashingVectorizer

vectorizer = HashingVectorizer(n_features=10)
hashed_representation = vectorizer.fit_transform([data])

hash = pd.DataFrame(hashed_representation.toarray())
hash

0         1         2         3         4         5         6  \
0  0.097088 -0.525854 -0.282916  0.027677  0.230199 -0.601855  0.059746   

          7         8         9  
0 -0.075561  0.385275 -0.245574

**Interpretasi Hasil :**

**Dari output di atas, kita dapat melihat bahwa Fitur 0, Fitur 3, Fitur 4, Fitur 6, dan Fitur 8 bernilai positif.  Ini artinya bahwa fitur tersebut lebih penting atau lebih relevan dalam cerita tersebut.Sementara Fitur 1, Fitur 2, Fitur 5, Fitur 7, dan Fitur 9 bernilai negatif. Ini artinya bahwa fitur tersebut kurang relevan dalam cerita tersebut.**

#**3. Co-occurance matrix**

In [9]:
vectorizer = CountVectorizer(tokenizer=lambda x: x.split(), ngram_range=(1, 1))
data_occur = vectorizer.fit_transform([data])
hasil = (data_occur.T * data_occur)
hasil.setdiag(0)

# Menyimpan hasil co-occurrence matrix ke dalam DataFrame
occurence = pd.DataFrame(hasil.toarray(), index=vectorizer.get_feature_names_out(), columns=vectorizer.get_feature_names_out())

# Menampilkan DataFrame
occurence

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


!  !"  !",  !".  !,"  !.    "  ",  "a...  "aaa...  ...  yet.  yik  \
!         0  33   44   11   22  11  264  22     11       11  ...    11   11   
!"       33   0   12    3    6   3   72   6      3        3  ...     3    3   
!",      44  12    0    4    8   4   96   8      4        4  ...     4    4   
!".      11   3    4    0    2   1   24   2      1        1  ...     1    1   
!,"      22   6    8    2    0   2   48   4      2        2  ...     2    2   
...      ..  ..  ...  ...  ...  ..  ...  ..    ...      ...  ...   ...  ...   
yosaku,  44  12   16    4    8   4   96   8      4        4  ...     4    4   
yosaku.  55  15   20    5   10   5  120  10      5        5  ...     5    5   
yuk!"    11   3    4    1    2   1   24   2      1        1  ...     1    1   
yut      11   3    4    1    2   1   24   2      1        1  ...     1    1   
zam!     11   3    4    1    2   1   24   2      1        1  ...     1    1   

         yikan  yir  yosaku  yosaku,  yosaku.  yuk!"  yut  zam!  
!           11   22     110       44       55     11   11    11  
!"           3    6      30       12       15      3    3     3  
!",          4    8      40       16       20      4    4     4  
!".          1    2      10        4        5      1    1     1  
!,"          2    4      20        8       10      2    2     2  
...        ...  ...     ...      ...      ...    ...  ...   ...  
yosaku,      4    8      40        0       20      4    4     4  
yosaku.      5   10      50       20        0      5    5     5  
yuk!"        1    2      10        4        5      0    1     1  
yut          1    2      10        4        5      1    0     1  
zam!         1    2      10        4        5      1    1     0  

[7647 rows x 7647 columns]

**Interpretasi Hasil :**

**Dari output di atas, kita dapat melihat bahwa pada baris dan kolom dengan label !, nilai 0 menunjukkan bahwa label ! tidak muncul bersama dirinya sendiri. Nilai 33 menunjukkan bahwa abel ! dan label !" muncul bersama sebanyak 33 kali, nilai 44 menunjukkan bahwa label ! dan label !", muncul bersama sebanyak 44 kali, dan seterusnya. Nilai 264 menunjukkan bahwa label ! dan label " muncul bersama sebanyak 264 kali.**

#**4.Word2Vec**

In [10]:
# Tokenisasi teks
sentences = sent_tokenize(data)
tokens = [word_tokenize(sentence.lower()) for sentence in sentences]

# Membangun model Word2Vec
model_word = Word2Vec(tokens, vector_size=10, window=3, min_count=1, workers=4)

# Mendapatkan representasi vektor kata
word_vectors = pd.DataFrame(model_word.wv.vectors, index=model_word.wv.index_to_key)

# Menampilkan top 5 kata dengan vektor tertinggi
top_words = word_vectors.sum(axis=1).nlargest(5).index
top_vectors = word_vectors.loc[top_words]

print("Top 5 kata dengan vektor tertinggi:")
top_vectors

Top 5 kata dengan vektor tertinggi:


0         1         2         3         4         5         6  \
dan    0.892795 -1.393628  3.764971 -0.365332 -0.220499  1.766067  1.855981   
yang   0.956512 -1.161441  3.250773 -0.287373 -0.128959  1.534896  1.492176   
untuk  0.737107 -1.171417  3.129591 -0.296461 -0.146223  1.619532  1.625579   
.      0.854424 -1.221584  3.225221 -0.145075 -0.305077  1.481616  1.634378   
di     0.907680 -1.055492  3.073012 -0.341480 -0.085537  1.533511  1.622890   

              7         8         9  
dan    1.821086 -3.348674 -1.307761  
yang   1.764191 -3.004569 -1.116108  
untuk  1.613183 -2.852177 -1.013823  
.      1.779472 -2.996984 -1.140940  
di     1.667316 -2.907425 -1.289846

**Interpretasi Hasil :**

**Dari output di atas, kita dapat melihat bahwa setiap baris mewakili kata dan vektor representasi kata dalam model Word2Vec. Misalnya, untuk kata "dan", vektor representasinya adalah [0.892795, -1.393628, 3.764971, -0.365332, -0.220499, 1.766067, 1.855981, 1.821086, -3.348674, -1.307761]. Ini adalah representasi vektor kata "dan" dalam dimensi yang ditentukan oleh model.**

#**5.Fast text**

In [11]:
# Membangun model fasttext
model_fast = FastText(tokens, vector_size=10, window=5, min_count=1, workers=4)

# Mendapatkan representasi vektor kata
vektor_kata = pd.DataFrame(model_fast.wv.vectors, index=model_fast.wv.index_to_key)

# Menampilkan top 5 kata dengan vektor tertinggi
top_fasttext = vektor_kata.sum(axis=1).nlargest(10000).index
top_textfast = vektor_kata.loc[top_fasttext]

print("Top 5 kata dengan vektor tertinggi:")
top_textfast

Top 5 kata dengan vektor tertinggi:


0         1         2         3         4         5         6  \
kan   2.916972  3.212567  0.539074  7.721177  3.376869  4.878800  4.687611   
an    2.697705  3.014228  0.469907  7.144464  3.120399  4.588743  4.362742   
meng  2.613316  2.938775  0.451732  7.021141  3.082499  4.484216  4.295458   
men   2.525124  2.913494  0.458783  6.869277  2.972396  4.381720  4.185894   
tan   2.284992  2.560417  0.411371  6.076718  2.642209  3.892784  3.697231   
...        ...       ...       ...       ...       ...       ...       ...   
999  -0.045684 -0.016717 -0.029194  0.036915  0.009197  0.012987 -0.012979   
12    0.012446  0.021883 -0.044744 -0.022848 -0.005505 -0.063774  0.057513   
'    -0.022061 -0.016191  0.005921  0.014059 -0.028968 -0.084622  0.006998   
20    0.040839  0.033242 -0.045786 -0.022730 -0.020977 -0.008441  0.006793   
o    -0.043428 -0.015373  0.002412  0.048238 -0.027280 -0.004456  0.028231   

             7         8         9  
kan   4.435620  0.191775  7.249630  
an    4.149093  0.195628  6.695942  
meng  4.031504  0.227458  6.537521  
men   3.906092  0.221767  6.456542  
tan   3.582080  0.152087  5.694000  
...        ...       ...       ...  
999   0.008196  0.017838  0.003036  
12    0.002284  0.015696 -0.006615  
'     0.039150 -0.019286  0.069683  
20    0.014511 -0.025794 -0.029607  
o    -0.023259 -0.080830  0.022989  

[5421 rows x 10 columns]

**Interpretasi Hasil :**

**Dari output di atas, kita dapat melihat bahwa lima kata teratas dengan vektor tertinggi adalah "kan," "an," "meng," "men," dan "tan." Untuk masing-masing kata, vektor representasinya terdiri dari 10 nilai numerik yang menggambarkan representasi kata tersebut dalam model FastText.**